#!/bin/bash
#
# chkconfig: 2345 70 78
# description: Boot up asset gather script to start the sark tool from the MSCF \
#              MASTER project

[ -r /etc/mcp.conf ] || exit 0

# Source the master path config
[ -f /etc/mcp-bin-dirs.sh ] && . /etc/mcp-bin-dirs.sh
MASTER_BIN_DIR=${MASTER_BIN_DIR:-/usr/bin}

case "$1" in
    start)
		/sbin/modprobe eeprom
		${MASTER_BIN_DIR}/sark >> /var/log/sark.log 2>&1
	;;
	*)
	echo "Usage: $0 start"
	;;
esac

exit 
