services:
  - karcaw/dind

stages:
 - build
 - deploy
 - extra

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  TILLER_NAMESPACE: "gitlab"

docker-image:
  stage: deploy
  tags:
    - docker
    - k8s
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$CI_JOB_NAME . -f Dockerfile
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$CI_JOB_NAME
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - master

build-centos7:
  stage: build
  script:
    - docker build -t master-build7 . -f Dockerfile.build
    - docker run -v `pwd`:/app/dist master-build7
  artifacts:
    paths:
      - ./*.rpm
    expire_in: 1 week
  tags:
    - docker

build-ubuntu1804:
  stage: build
  script:
    - docker build -t master-ubuntu-build . -f Dockerfile.build.dpkg
    - docker run -v `pwd`:/app/dist master-ubuntu-build
  artifacts:
    paths:
      - ./*.deb
    expire_in: 1 week
  tags:
    - docker

include: https://gitlab.emsl.pnl.gov/msc_ops/build/build-common/raw/master/k8s-artifact-deploy.yml
