services:
  - karcaw/dind

stages:
 - build
 - deploy
 - extra

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  TILLER_NAMESPACE: "gitlab"

centos7-build:
  stage: build
  script:
    - docker build -t master-build7 . -f Dockerfile.build
    - docker run -v `pwd`:/app/dist master-build7
  artifacts:
    paths:
      - ./*.rpm
    expire_in: 1 week
  tags:
    - docker

centos6-build:
  stage: build
  script:
    - sed -i -e s/centos:7/centos:6/ Dockerfile.build
    - docker build -t master-build6 . -f Dockerfile.build
    - docker run -v `pwd`:/app/dist master-build6
  artifacts:
    paths:
      - ./*.rpm
    expire_in: 1 week
  tags:
    - docker

ubuntu1604-build:
  stage: build
  script:
    - docker build -t master-ubuntu-build . -f Dockerfile.build.dpkg
    - docker run -v `pwd`:/app/dist master-ubuntu-build
  artifacts:
    paths:
      - ./*.deb
    expire_in: 1 week
  tags:
    - docker

deploy-centos7-k8s:
  stage: deploy
  dependencies:
    - centos7-build 
  only:
    - master
  script:
    - helm init --client-only
    - helm repo add repo  https://repo.emsl.pnl.gov/charts/
    - helm del --purge $CI_PROJECT_NAME || true
    - helm install -n $CI_PROJECT_NAME --set projectid=$CI_PROJECT_ID,pipelineid=$CI_PIPELINE_ID repo/artifact-repo

delete-centos7-k8s:
  stage: extra
  when: manual
  only:
    - master
  script:
    - helm del --purge $CI_PROJECT_NAME
