services:
  - karcaw/dind

stages:
 - build
 - deploy
 - extra

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  TILLER_NAMESPACE: "gitlab"

docker-image:
  stage: deploy
  tags:
    - docker
    - k8s
  script:
    - while true; do docker version > /dev/null && break; sleep 1; done
    - docker build -t $CI_REGISTRY_IMAGE/$CI_JOB_NAME . -f Dockerfile
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$CI_JOB_NAME
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - master

build-centos7:
  stage: build
  script:
    - while true; do docker version > /dev/null && break; sleep 1; done
    - docker build -t master-build7 . -f Dockerfile.build
    - docker run -v `pwd`:/app/dist master-build7
  artifacts:
    paths:
      - ./*.rpm
    expire_in: 1 week
  tags:
    - docker

build-rocky8:
  stage: build
  script:
    - while true; do docker version > /dev/null && break; sleep 1; done
    - docker build -t master-rocky-build . -f Dockerfile.build.rocky8
    - docker run -v `pwd`:/app/dist master-rocky-build
  artifacts:
    paths:
      - ./*.rpm
    expire_in: 1 week
  tags:
    - docker

build-rocky9:
  stage: build
  image:
      name: gcr.io/kaniko-project/executor:v1.9.0-debug
      entrypoint: [""]
  script:
    - echo $CI_PROJECT_DIR
    - ls $CI_PROJECT_DIR
    - /kaniko/executor --context dir://$CI_PROJECT_DIR/ --dockerfile $CI_PROJECT_DIR/Dockerfile.build.rocky9 --no-push
  artifacts:
    paths:
      - /app/dist
    expire_in: 1 week
  tags:
    - k8s

build-ubuntu2004:
  stage: build
  script:
    - while true; do docker version > /dev/null && break; sleep 1; done
    - docker build -t master-ubuntu-build . -f Dockerfile.build.dpkg
    - docker run -v `pwd`:/app/dist master-ubuntu-build
  artifacts:
    paths:
      - ./*.deb
    expire_in: 1 week
  tags:
    - docker

include:
    - https://gitlab.emsl.pnl.gov/msc_ops/build/build-common/raw/master/k8s-artifact-deploy.yml
    - https://gitlab.emsl.pnl.gov/msc_ops/build/build-common/raw/master/k8s-artifact-deploy-8.yml
