- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.0
  hooks:
  - id: trailing-whitespace
    exclude: web-pylons/master/master/public/js/*
  - id: end-of-file-fixer
  - id: check-yaml
  - id: autopep8-wrapper
  - id: check-docstring-first
  - id: check-added-large-files
  - id: debug-statements
