FROM rockylinux:9
LABEL org.opencontainers.image.authors="evan.felix@pnl.gov"
ARG DIR=/workspace

#ENV HTTPS_PROXY=http://proxy01.pnl.gov:3128
#ENV NO_PROXY="*.pnl.gov,*.pnnl.gov,127.0.0.1"

RUN dnf install -y python3 python3-pip rpm-build python3-devel postgresql-devel gcc
RUN pip3 install --upgrade pip
RUN pip3 install service_identity Twisted python-hostlist PyGreSQL pexpect

RUN cd $DIR && python3 setup.py bdist_rpm
RUN mkdir /output
RUN ls /app/dist
RUN cd /app && cp -a dist /output