FROM centos:7
MAINTAINER evan.felix@pnl.gov

RUN yum install -y python rpm-build hostparser python-twisted-core python-twisted-names python-twisted-web postgresql-python pexpect

COPY . /app

CMD cd /app && python setup.py bdist_rpm
