FROM rockylinux:9
LABEL org.opencontainers.image.authors="evan.felix@pnl.gov"

#ENV HTTPS_PROXY=http://proxy01.pnl.gov:3128
#ENV NO_PROXY="*.pnl.gov,*.pnnl.gov,127.0.0.1"

RUN dnf install -y python3 python3-pip rpm-build python3-devel postgresql-devel gcc
RUN pip3 install --upgrade pip
RUN pip3 install service_identity Twisted python-hostlist PyGreSQL expect


RUN python3 setup.py bdist_rpm
