# Default values for master-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gitlab.emsl.pnl.gov:4567/msc_ops/master/docker-image
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 627

database:
  server: master-database.emsl.pnl.gov
  name: master
  user: master
  password: setoneplease

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
