#!/bin/sh
#
# master-mcp: Run the mcp as part of the master project
#
# chkconfig: 2345 69 79
# description: Master Project
# config: /etc/mcp.conf /etc/mcp-priv.conf
#

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[  ${NETWORKING} = "no" ] && exit 0

# Source the master path config
[ -f /etc/mcp-bin-dirs.sh ] && . /etc/mcp-bin-dirs.sh
MASTER_SBIN_DIR=${MASTER_SBIN_DIR:-/usr/sbin}

# make sure mcp is installed and executable
[ -x ${MASTER_SBIN_DIR}/mcp  ] || exit 1
mcp=${MASTER_SBIN_DIR}/mcp

pidfile=${PIDFILE-/var/run/mcp.pid}
lockfile=${LOCKFILE-/var/lock/subsys/mcp}
STOP_TIMEOUT=${STOP_TIMEOUT-10}

RETVAL=0

start() {
    echo -n "Starting master-mcp: "
    daemon --pidfile=${pidfile} $mcp
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}
    return $RETVAL
}
stop() {
    echo -n "Shutting down master-mcp: "
    killproc -p ${pidfile} -d ${STOP_TIMEOUT} $mcp
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}
# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} $mcp
    RETVAL=$?
    ;;
  restart)
    echo -n "Restarting master-mcp: "
    stop
    start
    RETVAL=$?
    echo
    ;;
  *)
    echo "Usage: master-mcp {start|stop|restart|status}"
    exit 1
esac

exit $RETVAL
