apiVersion: v1
kind: Service
metadata:
  name: {{ include "master-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "master-server.name" . }}
    helm.sh/chart: {{ include "master-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 627
      protocol: TCP
      name: mcp
  selector:
    app.kubernetes.io/name: {{ include "master-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
